import {type NextPage} from "next";
import Head from "next/head";
import Link from "next/link";
import IconPhUser from '~icons/ph/user.jsx'

import {api} from "../utils/api";
import {Button, Card, theme, Typography} from "../components/UI";

const Home: NextPage = () => {
	const hello = api.example.hello.useQuery({text: "from tRPC"});
	
	const feedbacks = [
		{
			title: 'JavaScript',
			description: 'נועם עזר לי מאוד!! הוא מומחה בכול מה שקשור בפונקציות! ויש לו הבנה מעמיקה בבניית קוד נכון.',
			user: 'אורן אבו'
		},
		{
			title: 'React',
			description: 'נועם ישב איתי במשך שעתיים. הוא מתמצא מאוד בהוקים וראוטינג בריאקט.',
			user: 'אורן אבו'
		}
	]
	
	const handleAddFeedback = () => {
	
	}
	
	return (
		<>
			<Head>
				<title>Firgonim</title>
				<meta name="description" content="Generated by create-t3-app"/>
				<link rel="icon" href="/public/favicon.ico"/>
			</Head>
			<main dir="rtl" className="flex min-h-screen flex-col bg-[#f5f6fa]">
				<div className="flex h-full pt-10">
					<div className="flex flex-row px-10 mx-auto w-[1140px]">
						
						<div className="px-4">
							<Card
								className="flex p-4 flex-col items-center"
								height="430px"
								width="250px"
								noShadow>
								<div className="flex flex-col items-center">
									<div className="flex items-center justify-center mb-4 rounded-full bg-gray-200 h-20 w-20 text-3xl text-gray-500">
										<IconPhUser/>
									</div>
									
									<Typography variant={'h3'}>
										Noam Anisfeld
									</Typography>
									
									<Typography
										className="mt-2"
										weight={400}
										variant={'small'}
										color={theme.colors.gray_600}>
										Full Stack Developer
									</Typography>
								</div>
								
								<div className="flex flex-col items-center mt-10">
									<Typography
										variant={'h3'}
										color={theme.colors.blue_500}>
										About
									</Typography>
									
									<Typography
										className="mt-4"
										centered
										weight={400}
										variant={'small'}>
										Software and web programmer, expertising in frontend web technologies. Fast learner and always aim at thorough
										understanding. Code is my favorite music.
									</Typography>
								</div>
							</Card>
						</div>
						
						<div className="flex flex-col px-4 space-y-4 w-full">
							{feedbacks.map(feedback => (
								<Card
									className="p-4"
									width="100%"
									height="fit-content"
									key={feedback.title}
									noShadow>
									<div className="flex flex-col space-y-2 w-[50%]">
										<Typography variant={'body'} color={theme.colors.blue_500}>
											{feedback.title}
										</Typography>
										
										<Typography
											weight={400}
											variant={'body'}>
											{feedback.description}
										</Typography>
									</div>
									
									<div className="flex justify-end">
										<Typography
											weight={400}
											color={theme.colors.gray_500}
											variant={'body'}>
											{feedback.user}
										</Typography>
									</div>
								</Card>
							))}
							
							<div className="flex">
								<Button onClick={handleAddFeedback} noShadow>
									<Typography
										weight={400}
										color={theme.colors.gray_500}
										variant={'body'}>
										הוספת פירגון
									</Typography>
								</Button>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
};

export default Home;
